# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-17 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170617_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
