# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-17 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170618_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='capacities',
            field=models.ManyToManyField(to='catalog.Capacity'),
        ),
    ]
