# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170618_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Participant'),
        ),
    ]
