# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170618_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='owner_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participation',
            name='participant_validation',
            field=models.BooleanField(default=False),
        ),
    ]
