# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170618_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('created', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='AccessoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Accessory Categories',
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('created', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('created', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('storage', models.CharField(max_length=10, null=True)),
                ('path', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200, null=True)),
                ('postal_code', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('gps_lat', models.CharField(max_length=200, null=True)),
                ('gps_lon', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='object',
            name='category',
        ),
        migrations.RemoveField(
            model_name='object',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='objectcategory',
            name='creator',
        ),
        migrations.AlterModelOptions(
            name='capacity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Capacities'},
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.DeleteModel(
            name='ObjectCategory',
        ),
        migrations.AddField(
            model_name='decor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Location'),
        ),
        migrations.AddField(
            model_name='decor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Participant'),
        ),
        migrations.AddField(
            model_name='decor',
            name='photos',
            field=models.ManyToManyField(to='catalog.Image'),
        ),
        migrations.AddField(
            model_name='actor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Location'),
        ),
        migrations.AddField(
            model_name='actor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Participant'),
        ),
        migrations.AddField(
            model_name='actor',
            name='photos',
            field=models.ManyToManyField(to='catalog.Image'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.ManyToManyField(to='catalog.AccessoryCategory'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Location'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Participant'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='photos',
            field=models.ManyToManyField(to='catalog.Image'),
        ),
    ]
