# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170621_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('created', models.DateField(null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Participant')),
                ('photos', models.ManyToManyField(to='catalog.Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='label',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='created',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='label',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='created',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='label',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='photos',
        ),
        migrations.AddField(
            model_name='accessory',
            name='object_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Object'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='object_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Object'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decor',
            name='object_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Object'),
            preserve_default=False,
        ),
    ]
