# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-01 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170621_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
